server:
  port: 8000

spring:
  batch:
    jdbc:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/one_punch?currentSchema=usr
    username: root
    password: root

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate:
      debug