name: One Punch

on:
  push:
    branches:
      - "prod"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build Boot Jar
        run: |
          ./gradlew :app:bootJar

      - name: Generate Private key
        run: |
          echo '${{ secrets.SSH_PRIVATE_KEY }}' > ./id_rsa
          chmod 0600 ./id_rsa

      - name: Transfer
        run: |
          scp -o StrictHostKeyChecking=no -i ./id_rsa -r ./app/build/libs/app.jar root@warrior.hihusky.com:~/one-punch-api.jar

      - name: Rerun in Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ./id_rsa root@warrior.hihusky.com "fuser -k 8080/tcp"
          ssh -o StrictHostKeyChecking=no -i ./id_rsa root@warrior.hihusky.com "nohup java -jar one-punch-api.jar > /dev/null 2>&1 &"